# Generated by Django 3.1.3 on 2020-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('countrycode', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=128)),
                ('newconfirmed', models.IntegerField()),
                ('totalconfirmed', models.IntegerField()),
                ('totaldeaths', models.IntegerField()),
                ('newrecovered', models.IntegerField()),
                ('totalrecovered', models.IntegerField()),
            ],
            options={
                'verbose_name': 'covid19',
                'verbose_name_plural': 'covid19s',
            },
        ),
    ]
